// Every user-facing lfg text (M4 spec §4.4): English defaults (BBDC 13.2) in
// one object. textOf(config, key, vars) takes config.texts[key] when the web
// (M5) has set an override, and fills "{name}" placeholders from `vars`. An
// unknown key throws — a typo must fail a test, not show "undefined".
const DEFAULTS = Object.freeze({
  // channel panel + board
  panelTitle: "Want a game?",
  panelSub: "Start a search, or pick roles to get pinged.",
  startButton: "Start my own search",
  rolesPlaceholder: "Pick your roles…",
  segStarted: "Just started",
  segFixed: "Fixed",
  segTimed: "Timed",
  segNow: "Now",
  boardEmpty: "No one is looking right now.",
  boardMore: "+{n} more — open /menu › Browse",
  waitingBoth: "waiting for both to confirm",
  interested: "{n} interested",
  ping: "{roles} **{poster}** is looking for **{label}** · {when}",
  newSearchDm: "**{poster}** is looking for **{label}** · {when} — {link}",
  // the searcher's thread
  threadIntro: "Your search is live. Requests show up below in the order they came in — tap Accept on the one you want.",
  requestsTitle: "Requests",
  removedTitle: "Removed",
  panelEmpty: "-# No requests yet.",
  moreRequests: "-# +{n} more waiting",
  cancelSearch: "Cancel search",
  joinNotify: "<@{poster}> **{joiner}** wants to join · {n} waiting",
  welcome: "WAKEY-WAKEY! <@{poster}> you accepted **{joiner}** for **{label}**.",
  welcomePing: "WAKEY-WAKEY! <@{poster}> you accepted <@{joiner}> for **{label}**.",
  confirmTitle: "Confirm",
  confirmWaitTimed: "-# You'll be asked to confirm {lead} minutes before the start ({when}).",
  confirmOnHold: "-# On hold until you both confirm: {names} · ends {when}",
  confirmEnds: "-# ends {when}",
  confirmDone: "✓ Game on",
  hereButton: "I'm here",
  headsUp: "Heads up <@{poster}> — your game starts {when}!",
  headsUpBoth: "Heads up <@{poster}> <@{joiner}> — your game starts {when}!",
  nag: "<@{user}> — tap I'm here when you're ready.",
  gameOn: "Game on!",
  gameOnSub: "-# **{poster}** + **{partner}** · {label} · good luck",
  reopened: "**{joiner}** didn't confirm — your search is open again. Pick someone else from the list.",
  reopenedLeft: "**{joiner}** left — your search is open again. Pick someone else from the list.",
  closedExpired: "Search expired.",
  closedCancelled: "Search cancelled.",
  closedRemoved: "Search removed by an officer.",
  closedNoConfirm: "Search closed — not confirmed in time.",
  // removed-box reasons
  reason_matched_elsewhere: "joined another game",
  reason_self: "cancelled",
  reason_no_confirm: "didn't confirm",
  reason_filled: "game is full",
  reason_expired: "expired",
  reason_cancelled: "search cancelled",
  reason_removed: "removed",
  // DM card
  yourRequest: "Your request",
  yourRequests: "Your requests",
  stillOpen: "Still open",
  alsoAccepted: "Also picked you",
  acceptedRow: "-# accepted — starts {when}",
  waitingLine: "-# waiting · you're #{n} · {when}",
  onHoldLine: "-# on hold — you're next if it falls through",
  cancelButton: "Cancel",
  cancelAll: "Cancel all",
  joinButton: "Join",
  acceptButton: "Accept",
  openThread: "Open the thread",
  youreIn: "You're in!",
  youreInSub: "-# {emoji} {label} · {when} — **{poster}** picked you.",
  confirmCardHint: "The game is set once you both tap I'm here. Your other requests stay on hold until then.",
  gameOnCard: "✓ Game on!",
  otherCancelled: "Your other requests were cancelled.",
  cardEmpty: "-# You have no open requests right now.",
  cardReplaced: "This card was replaced by a newer one.",
  event_full: "{name}'s game is full",
  event_full_sub: "someone else got the spot.",
  event_expired: "{name}'s search expired",
  event_expired_sub: "no one was picked in time.",
  event_cancelled: "{name}'s search was cancelled",
  event_cancelled_sub: "the search is closed.",
  event_posterNoConfirm: "{name} didn't confirm",
  event_posterNoConfirm_sub: "the game didn't start.",
  event_noConfirm: "You didn't confirm in time",
  event_noConfirm_sub: "the spot went back to the queue.",
  // replies
  threadFailed: "I couldn't open your search thread, so the search was cancelled. Try again in a minute.",
  requestSent: "Request sent to **{poster}** — you're #{n} in line. Updates come in your DMs.",
  requestSentNoDm: "Request sent to **{poster}** — you're #{n} in line. Your DMs are closed — check Menu › Teammates.",
  alreadyRequested: "You already asked to join **{poster}**'s search — you're #{n} in line.",
  alreadyAccepted: "**{poster}** already picked you — check your DMs or the thread.",
  requestCancelled: "Request cancelled.",
  requestsCancelled: "Cancelled {n} requests.",
  searchCancelled: "Search cancelled.",
  searchRemoved: "Removed **{poster}**'s search.",
  hereAlready: "You already tapped I'm here.",
  hereTooEarly: "Not yet — you'll be asked to confirm {lead} minutes before the start.",
  // errors
  notSetUp: "Teammates isn't set up yet — ask an admin.",
  notOpen: "That search isn't open anymore.",
  spotTaken: "That spot was already taken.",
  notYours: "Only the searcher can do that.",
  notInGame: "Only the two players can confirm.",
  ownSearch: "That's your own search.",
  busy: "You're in a game right now — try again when it's over.",
  hasSearch: "You already have a search open.",
  noRequest: "You have no open request there.",
  requestGone: "That request isn't there anymore.",
  noRequests: "You have no open requests.",
  gameStarted: "That game has already started.",
  needLookingFor: "Pick what you're looking for.",
  badOption: "That option isn't available anymore — pick again.",
  badMinutes: "Starts in: a whole number of minutes from 0 to 1440 (empty = now).",
  noteTooLong: "Keep the note to 100 characters or fewer.",
  favoriteStale: "That favorite is out of date — pick a custom search.",
  forbidden: "You can't do that.",
  officerOnly: "Only officers can remove a search.",
  roleFailed: "I couldn't change that role — ask an admin to check my permissions.",
  cancelMySearch: "Cancel my search",
  cancelRequest: "Cancel request",
});

function textOf(config, key, vars = {}) {
  if (!Object.hasOwn(DEFAULTS, key)) throw new Error(`[lfg] unknown text key "${key}"`);
  const override = config && config.texts && typeof config.texts[key] === "string" ? config.texts[key] : null;
  return (override ?? DEFAULTS[key]).replace(/\{(\w+)\}/g, (m, name) => (Object.hasOwn(vars, name) ? String(vars[name]) : m));
}

module.exports = { DEFAULTS, textOf };
